services:
  - type: web
    name: Aamon-FL
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9090
    healthCheckPath: /
    autoDeploy: true
