name: NPM Audit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high
